create user apppro identified by admin;
grant resource to apppro;
grant connect to apppro;



------tablas
 CREATE TABLE "APPPRO"."PRO_AFILIADO" 
   (	"AFI_ID" NUMBER, 
	"AFI_NOMBRES" VARCHAR2(150 BYTE), 
	"AFI_APEPATERNO" VARCHAR2(50 BYTE), 
	"AFI_APEMATERNO" VARCHAR2(50 BYTE), 
	"AFI_ESTADO" CLOB DEFAULT 1, 
	"AFI_FECNAC" DATE, 
	"AFI_EDAD" NUMBER, 
	"AFI_SEXO" CHAR(1 BYTE), 
	"AFI_TELEFONO" VARCHAR2(20 BYTE), 
	"AFI_DNI" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("AFI_ESTADO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "APPPRO"."PRO_AFILIADO"."AFI_ESTADO" IS 'ESTADO AFILIADO';
--------------------------------------------------------
--  DDL for Table PRO_ATENCION
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_ATENCION" 
   (	"ATE_ID" NUMBER, 
	"AFI_ID" NUMBER, 
	"ATE_FECATE" TIMESTAMP (6), 
	"ATE_USUATE" VARCHAR2(30 BYTE), 
	"ATE_OBSERVACION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRO_ATENCIONDIA
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_ATENCIONDIA" 
   (	"ATD_ID" NUMBER, 
	"ATE_ID" NUMBER, 
	"DIA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRO_ATENCIONPRO
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_ATENCIONPRO" 
   (	"ATP_ID" NUMBER, 
	"ATE_ID" NUMBER, 
	"PRO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRO_IDENTITY_TABLAS
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_IDENTITY_TABLAS" 
   (	"IDE_NOMBRE_TABLA" VARCHAR2(50 BYTE), 
	"IDE_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRO_MAEDIAGNOSTICO
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_MAEDIAGNOSTICO" 
   (	"DIA_COD" VARCHAR2(20 BYTE), 
	"DIA_DESCRIPCION" VARCHAR2(100 BYTE), 
	"DIA_ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRO_MAEPIEZA
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_MAEPIEZA" 
   (	"PIEZA_ID" NUMBER, 
	"PIEZA_IDENTIFICA" VARCHAR2(20 BYTE), 
	"PIEZA_PARTE" VARCHAR2(20 BYTE), 
	"PIEZA_PARTE_NOMBRE" VARCHAR2(50 BYTE), 
	"PIEZA_NUMERO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRO_MAEPROCEDIMIENTO
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_MAEPROCEDIMIENTO" 
   (	"PRO_COD" VARCHAR2(10 BYTE), 
	"PRO_DESCRIPCION" VARCHAR2(100 BYTE), 
	"PRO_ESTADO" CHAR(1 BYTE), 
	"PRO_COSTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRO_PIEZA
--------------------------------------------------------

  CREATE TABLE "APPPRO"."PRO_PIEZA" 
   (	"PIEZA_ID" NUMBER, 
	"PIEZA_IDENTIFICA" VARCHAR2(20 BYTE), 
	"PIEZA_PARTE" VARCHAR2(20 BYTE), 
	"PIEZA_PARTE_NOMBRE" VARCHAR2(50 BYTE), 
	"PIEZA_NUMERO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_ROLES
--------------------------------------------------------

  CREATE TABLE "APPPRO"."USER_ROLES" 
   (	"ROLE_ID" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(36 BYTE), 
	"USER_ROLE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "APPPRO"."USERS" 
   (	"USERNAME" VARCHAR2(36 BYTE), 
	"PASSWORD" VARCHAR2(36 BYTE), 
	"ESTADO" NUMBER(1,0), 
	"NOMBRES" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into APPPRO.PRO_AFILIADO
SET DEFINE OFF;
Insert into APPPRO.PRO_AFILIADO (AFI_ID,AFI_NOMBRES,AFI_APEPATERNO,AFI_APEMATERNO,AFI_FECNAC,AFI_EDAD,AFI_SEXO,AFI_TELEFONO,AFI_DNI) values ('1','PEPITO','LLOPEZ','CONTRERAS',to_date('01/06/13','DD/MM/RR'),'33','M','45488552','08999999');
Insert into APPPRO.PRO_AFILIADO (AFI_ID,AFI_NOMBRES,AFI_APEPATERNO,AFI_APEMATERNO,AFI_FECNAC,AFI_EDAD,AFI_SEXO,AFI_TELEFONO,AFI_DNI) values ('2','LUISA','HERNADEZ','FERNANDEZ',to_date('01/06/13','DD/MM/RR'),'27','F','96955882','09888888');
Insert into APPPRO.PRO_AFILIADO (AFI_ID,AFI_NOMBRES,AFI_APEPATERNO,AFI_APEMATERNO,AFI_FECNAC,AFI_EDAD,AFI_SEXO,AFI_TELEFONO,AFI_DNI) values ('3','JUAN','AGUIRRE','LOLI',to_date('04/04/62','DD/MM/RR'),'56','M','922356478','08956280');
Insert into APPPRO.PRO_AFILIADO (AFI_ID,AFI_NOMBRES,AFI_APEPATERNO,AFI_APEMATERNO,AFI_FECNAC,AFI_EDAD,AFI_SEXO,AFI_TELEFONO,AFI_DNI) values ('4','LUZMILA','FARIS','HUERTA',to_date('19/04/52','DD/MM/RR'),'66','F','974625801','08956282');
Insert into APPPRO.PRO_AFILIADO (AFI_ID,AFI_NOMBRES,AFI_APEPATERNO,AFI_APEMATERNO,AFI_FECNAC,AFI_EDAD,AFI_SEXO,AFI_TELEFONO,AFI_DNI) values ('5','PATRICIA','CORONADO','FARIS',to_date('18/02/85','DD/MM/RR'),'33','F','974625801','42949905');
REM INSERTING into APPPRO.PRO_ATENCION
SET DEFINE OFF;
REM INSERTING into APPPRO.PRO_ATENCIONDIA
SET DEFINE OFF;
REM INSERTING into APPPRO.PRO_ATENCIONPRO
SET DEFINE OFF;
REM INSERTING into APPPRO.PRO_IDENTITY_TABLAS
SET DEFINE OFF;
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_AFILIADO','5');
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_ATENCION','0');
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_ATENCIONDIA','0');
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_ATENCIONPRO','0');
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_MAEDIAGNOSTICO','6');
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_MAEPIEZA','0');
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_MAEPROCEDIMIENTO','12');
Insert into APPPRO.PRO_IDENTITY_TABLAS (IDE_NOMBRE_TABLA,IDE_NUM) values ('PRO_PIEZA','160');
REM INSERTING into APPPRO.PRO_MAEDIAGNOSTICO
SET DEFINE OFF;
Insert into APPPRO.PRO_MAEDIAGNOSTICO (DIA_COD,DIA_DESCRIPCION,DIA_ESTADO) values ('K020','CARIES DEL ESMALTE','1');
Insert into APPPRO.PRO_MAEDIAGNOSTICO (DIA_COD,DIA_DESCRIPCION,DIA_ESTADO) values ('K021','CARIES DENTINA','1');
Insert into APPPRO.PRO_MAEDIAGNOSTICO (DIA_COD,DIA_DESCRIPCION,DIA_ESTADO) values ('K040','PULPITIS','1');
Insert into APPPRO.PRO_MAEDIAGNOSTICO (DIA_COD,DIA_DESCRIPCION,DIA_ESTADO) values ('K041','NECROSIS PULPAR','1');
Insert into APPPRO.PRO_MAEDIAGNOSTICO (DIA_COD,DIA_DESCRIPCION,DIA_ESTADO) values ('K050','GINGIVITIS AGUDA','1');
Insert into APPPRO.PRO_MAEDIAGNOSTICO (DIA_COD,DIA_DESCRIPCION,DIA_ESTADO) values ('Z012','SANO','1');
REM INSERTING into APPPRO.PRO_MAEPIEZA
SET DEFINE OFF;
REM INSERTING into APPPRO.PRO_MAEPROCEDIMIENTO
SET DEFINE OFF;
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('232101','OBTURACION DENTAL POR SUPERFICIE CON AMALGAMA','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('232102','OBTURACION DENTAL POR SUPERFICIE CON RESINA DE FOTOCURADO','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('232103','OBTURACION DENTAL POR SUPERFICIE CON IONOMERO DE VIDRIO','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('232200','OBTURACION TEMPORAL POR DIENTE','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('232200','OBTURACION TEMPORAL POR DIENTE','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('237102','PULPOTOMIA CON PULPECTOMIA','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('240200','DETARTRAJE SUBGINGIVAL (POR CUADRANTE)','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('997301','DETARTRAJE SUPRAGINGIVAL','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('997500','PROFILAXIS DENTAL','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('997102','APLICACION DE SELLANTES DE FOTOCURADO','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('997103','TOPICACION DE FLUOR EN GEL','1','10');
Insert into APPPRO.PRO_MAEPROCEDIMIENTO (PRO_COD,PRO_DESCRIPCION,PRO_ESTADO,PRO_COSTO) values ('997104','TOPICACION DE FLUOR EN SOLUCION','1','10');
REM INSERTING into APPPRO.PRO_PIEZA
SET DEFINE OFF;
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('1','M11','O','OCLUSAL','11');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('2','M11','P1','VESTIBULAR','11');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('3','M11','P2','MESIAL','11');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('4','M11','P3','PALATINO','11');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('5','M11','P4','DISTAL','11');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('6','M12','O','OCLUSAL','12');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('7','M12','P1','VESTIBULAR','12');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('8','M12','P2','MESIAL','12');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('9','M12','P3','PALATINO','12');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('10','M12','P4','DISTAL','13');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('11','M13','O','OCLUSAL','13');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('12','M13','P1','VESTIBULAR','13');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('13','M13','P2','MESIAL','13');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('14','M13','P3','PALATINO','13');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('15','M13','P4','DISTAL','14');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('16','M14','O','OCLUSAL','14');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('17','M14','P1','VESTIBULAR','14');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('18','M14','P2','MESIAL','14');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('19','M14','P3','PALATINO','14');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('20','M14','P4','DISTAL','15');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('21','M15','O','OCLUSAL','15');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('22','M15','P1','VESTIBULAR','15');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('23','M15','P2','MESIAL','15');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('24','M15','P3','PALATINO','15');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('25','M15','P4','DISTAL','16');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('26','M16','O','OCLUSAL','16');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('27','M16','P1','VESTIBULAR','16');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('28','M16','P2','MESIAL','16');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('29','M16','P3','PALATINO','16');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('30','M16','P4','DISTAL','17');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('31','M17','O','OCLUSAL','17');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('32','M17','P1','VESTIBULAR','17');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('33','M17','P2','MESIAL','17');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('34','M17','P3','PALATINO','17');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('35','M17','P4','DISTAL','18');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('36','M18','O','OCLUSAL','18');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('37','M18','P1','VESTIBULAR','18');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('38','M18','P2','MESIAL','18');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('39','M18','P3','PALATINO','18');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('40','M18','P4','DISTAL','21');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('41','M21','O','OCLUSAL','21');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('42','M21','P1','VESTIBULAR','21');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('43','M21','P2','DISTAL','21');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('44','M21','P3','PALATINO','21');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('45','M21','P4','MESIAL','22');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('46','M22','O','OCLUSAL','22');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('47','M22','P1','VESTIBULAR','22');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('48','M22','P2','DISTAL','22');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('49','M22','P3','PALATINO','22');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('50','M22','P4','MESIAL','23');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('51','M23','O','OCLUSAL','23');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('52','M23','P1','VESTIBULAR','23');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('53','M23','P2','DISTAL','23');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('54','M23','P3','PALATINO','23');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('55','M23','P4','MESIAL','24');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('56','M24','O','OCLUSAL','24');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('57','M24','P1','VESTIBULAR','24');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('58','M24','P2','DISTAL','24');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('59','M24','P3','PALATINO','24');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('60','M24','P4','MESIAL','25');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('61','M25','O','OCLUSAL','25');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('62','M25','P1','VESTIBULAR','25');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('63','M25','P2','DISTAL','25');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('64','M25','P3','PALATINO','25');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('65','M25','P4','MESIAL','26');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('66','M26','O','OCLUSAL','26');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('67','M26','P1','VESTIBULAR','26');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('68','M26','P2','DISTAL','26');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('69','M26','P3','PALATINO','26');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('70','M26','P4','MESIAL','27');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('71','M27','O','OCLUSAL','27');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('72','M27','P1','VESTIBULAR','27');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('73','M27','P2','DISTAL','27');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('74','M27','P3','PALATINO','27');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('75','M27','P4','MESIAL','28');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('76','M28','O','OCLUSAL','28');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('77','M28','P1','VESTIBULAR','28');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('78','M28','P2','DISTAL','28');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('79','M28','P3','PALATINO','28');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('80','M28','P4','MESIAL','31');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('81','M31','O','OCLUSAL','31');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('82','M31','P1','LINGUAL','31');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('83','M31','P2','DISTAL','31');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('84','M31','P3','VESTIBULAR','31');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('85','M31','P4','MESIAL','32');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('86','M32','O','OCLUSAL','32');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('87','M32','P1','LINGUAL','32');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('88','M32','P2','DISTAL','32');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('89','M32','P3','VESTIBULAR','32');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('90','M32','P4','MESIAL','33');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('91','M33','O','OCLUSAL','33');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('92','M33','P1','LINGUAL','33');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('93','M33','P2','DISTAL','33');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('94','M33','P3','VESTIBULAR','33');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('95','M33','P4','MESIAL','34');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('96','M34','O','OCLUSAL','34');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('97','M34','P1','LINGUAL','34');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('98','M34','P2','DISTAL','34');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('99','M34','P3','VESTIBULAR','34');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('100','M34','P4','MESIAL','35');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('101','M35','O','OCLUSAL','35');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('102','M35','P1','LINGUAL','35');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('103','M35','P2','DISTAL','35');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('104','M35','P3','VESTIBULAR','35');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('105','M35','P4','MESIAL','36');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('106','M36','O','OCLUSAL','36');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('107','M36','P1','LINGUAL','36');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('108','M36','P2','DISTAL','36');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('109','M36','P3','VESTIBULAR','36');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('110','M36','P4','MESIAL','37');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('111','M37','O','OCLUSAL','37');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('112','M37','P1','LINGUAL','37');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('113','M37','P2','DISTAL','37');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('114','M37','P3','VESTIBULAR','37');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('115','M37','P4','MESIAL','38');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('116','M38','O','OCLUSAL','38');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('117','M38','P1','LINGUAL','38');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('118','M38','P2','DISTAL','38');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('119','M38','P3','VESTIBULAR','38');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('120','M38','P4','MESIAL','41');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('121','M41','O','OCLUSAL','41');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('122','M41','P1','LINGUAL','41');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('123','M41','P2','MESIAL','41');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('124','M41','P3','VESTIBULAR','41');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('125','M41','P4','DISTAL','42');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('126','M42','O','OCLUSAL','42');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('127','M42','P1','LINGUAL','42');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('128','M42','P2','MESIAL','42');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('129','M42','P3','VESTIBULAR','42');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('130','M42','P4','DISTAL','43');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('131','M43','O','OCLUSAL','43');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('132','M43','P1','LINGUAL','43');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('133','M43','P2','MESIAL','43');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('134','M43','P3','VESTIBULAR','43');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('135','M43','P4','DISTAL','44');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('136','M44','O','OCLUSAL','44');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('137','M44','P1','LINGUAL','44');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('138','M44','P2','MESIAL','44');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('139','M44','P3','VESTIBULAR','44');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('140','M44','P4','DISTAL','45');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('141','M45','O','OCLUSAL','45');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('142','M45','P1','LINGUAL','45');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('143','M45','P2','MESIAL','45');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('144','M45','P3','VESTIBULAR','45');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('145','M45','P4','DISTAL','46');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('146','M46','O','OCLUSAL','46');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('147','M46','P1','LINGUAL','46');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('148','M46','P2','MESIAL','46');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('149','M46','P3','VESTIBULAR','46');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('150','M46','P4','DISTAL','47');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('151','M47','O','OCLUSAL','47');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('152','M47','P1','LINGUAL','47');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('153','M47','P2','MESIAL','47');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('154','M47','P3','VESTIBULAR','47');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('155','M47','P4','DISTAL','48');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('156','M48','O','OCLUSAL','48');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('157','M48','P1','LINGUAL','48');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('158','M48','P2','MESIAL','48');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('159','M48','P3','VESTIBULAR','48');
Insert into APPPRO.PRO_PIEZA (PIEZA_ID,PIEZA_IDENTIFICA,PIEZA_PARTE,PIEZA_PARTE_NOMBRE,PIEZA_NUMERO) values ('160','M48','P4','DISTAL','48');
REM INSERTING into APPPRO.USER_ROLES
SET DEFINE OFF;
Insert into APPPRO.USER_ROLES (ROLE_ID,USERNAME,USER_ROLE) values ('2','dbadmin1','ADMINISTRADOR');
Insert into APPPRO.USER_ROLES (ROLE_ID,USERNAME,USER_ROLE) values ('3','dbuser2','USUARIO');
Insert into APPPRO.USER_ROLES (ROLE_ID,USERNAME,USER_ROLE) values ('1','dbuser1','USUARIO');
REM INSERTING into APPPRO.USERS
SET DEFINE OFF;
Insert into APPPRO.USERS (USERNAME,PASSWORD,ESTADO,NOMBRES,APELLIDOS) values ('dbuser1','12345','1','JUAN','MINCHOLA');
Insert into APPPRO.USERS (USERNAME,PASSWORD,ESTADO,NOMBRES,APELLIDOS) values ('dbadmin1','12345','1','PATRICIA','CORONADO');
--------------------------------------------------------
--  DDL for Index USER_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."USER_ROLE_PK" ON "APPPRO"."USER_ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRO_ATENCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."PRO_ATENCION_PK" ON "APPPRO"."PRO_ATENCION" ("ATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."USER_PK" ON "APPPRO"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRO_AFILIADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."PRO_AFILIADO_PK" ON "APPPRO"."PRO_AFILIADO" ("AFI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_ROLE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPPRO"."USER_ROLE_UK" ON "APPPRO"."USER_ROLES" ("USERNAME", "USER_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRO_ATENCION
--------------------------------------------------------

  ALTER TABLE "APPPRO"."PRO_ATENCION" ADD CONSTRAINT "PRO_ATENCION_PK" PRIMARY KEY ("ATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPPRO"."PRO_ATENCION" MODIFY ("ATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "APPPRO"."USERS" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPPRO"."USERS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "APPPRO"."USER_ROLES" ADD CONSTRAINT "USER_ROLE_UK" UNIQUE ("USERNAME", "USER_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPPRO"."USER_ROLES" ADD CONSTRAINT "USER_ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APPPRO"."USER_ROLES" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USER_ROLES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRO_AFILIADO
--------------------------------------------------------

  ALTER TABLE "APPPRO"."PRO_AFILIADO" MODIFY ("AFI_ID" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."PRO_AFILIADO" ADD CONSTRAINT "PRO_AFILIADO_PK" PRIMARY KEY ("AFI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRO_MAEDIAGNOSTICO
--------------------------------------------------------

  ALTER TABLE "APPPRO"."PRO_MAEDIAGNOSTICO" MODIFY ("DIA_DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "APPPRO"."PRO_MAEDIAGNOSTICO" MODIFY ("DIA_COD" NOT NULL ENABLE);




  CREATE OR REPLACE FORCE VIEW "APPPRO"."W_PRO_AFILIADO" ("AFI_ID", "AFI_NOMBRES", "AFI_APEPATERNO", "AFI_APEMATERNO", "AFI_ESTADO", "AFI_FECNAC", "AFI_EDAD", "AFI_SEXO", "AFI_TELEFONO", "AFI_DNI") AS 
  SELECT "AFI_ID","AFI_NOMBRES","AFI_APEPATERNO","AFI_APEMATERNO","AFI_ESTADO","AFI_FECNAC","AFI_EDAD","AFI_SEXO","AFI_TELEFONO","AFI_DNI"    FROM APPPRO.PRO_AFILIADO
;
--------------------------------------------------------
--  DDL for View W_PRO_LOGUEO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "APPPRO"."W_PRO_LOGUEO" ("USERNAME", "PASSWORD", "USER_ROLE", "ESTADO", "NOMBRES", "APELLIDOS") AS 
  SELECT U.USERNAME,PASSWORD,USER_ROLE, ESTADO , NOMBRES ,
APELLIDOS from USERS U INNER JOIN USER_ROLES R ON U.USERNAME=R.USERNAME
;
